-- AlterTable
ALTER TABLE "User" ADD COLUMN "emailVerifiedAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "phoneVerifiedAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "kycStatus" TEXT NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE "User" ADD COLUMN "kycNotes" TEXT;
ALTER TABLE "User" ADD COLUMN "kycReviewedAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "trustScore" INTEGER NOT NULL DEFAULT 0;