ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "agentValidationStatus" TEXT NOT NULL DEFAULT 'NOT_APPLICABLE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "agentValidationNote" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "agentReviewedAt" TIMESTAMP(3);
