ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "isSuspicious" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "suspiciousReason" TEXT;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "isReportedAsAbuse" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "abuseReason" TEXT;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "abuseReportedAt" TIMESTAMP(3);

ALTER TABLE "ProductRequest" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ProductRequest" ADD COLUMN IF NOT EXISTS "isSuspicious" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ProductRequest" ADD COLUMN IF NOT EXISTS "suspiciousReason" TEXT;
ALTER TABLE "ProductRequest" ADD COLUMN IF NOT EXISTS "markedAsScam" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ProductRequest" ADD COLUMN IF NOT EXISTS "scamReason" TEXT;
ALTER TABLE "ProductRequest" ADD COLUMN IF NOT EXISTS "scamMarkedAt" TIMESTAMP(3);

CREATE UNIQUE INDEX IF NOT EXISTS "ProductRequest_acceptedOfferId_key" ON "ProductRequest"("acceptedOfferId");
